apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mlflow-server
  template:
    metadata:
      labels:
        name: mlflow-server
    spec:
      serviceAccountName: <sa-account>
      containers:
        - image: "quay.io/harshad16/mlflow:v0.1.1"
          imagePullPolicy: IfNotPresent
          name: mlflow
          command: 
            - mlflow
          args:
            - server
            - '--host'
            - '0.0.0.0'
            - '--backend-store-uri'
            - 'postgresql://<db-user>:<db-pwd>@postgresql.<namespace>.svc:5432/<db-name>?sslmode=disable'
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            requests:
              cpu: "500m"
              memory: 1Gi
            limits:
              cpu: "500m"
              memory: 1Gi
